CanFrame frame
---
int8 status

# OK
int8 STATUS_OK=0
# Data Formatting Error
int8 STATUS_ERROR_INVALID_ID=1
int8 STATUS_ERROR_DLC_OUT_OF_RANGE=2
#Socket / Interface Error
int8 STATUS_ERROR_SOCKET_NOT_OPEN=11
int8 STATUS_ERROR_PARTIAL_FRAME_SENT=12
int8 STATUS_ERROR_UNABLE_TO_SEND_DATA=13